### ISSUE TITLE
Adjust height if textarea uses alternate box model

### ISSUE THREAD

**Issue by mcavalletto** [flaviusmatis/flexibleArea.js#3]
If the text area uses the alternate CSS box model, then the height needs to be increased by the amount of the padding and border.

The alternate box model is not common, but it is sometimes used in this context to allow textareas to be made to lay out correctly when set to width: 100%.

Solution is the addition of the following lines.

```
    function setHeightAndOverflow(){
        var cloneHeight = $clone.height() + lineHeight;
        var overflow = 'hidden';
        var height = cloneHeight;
+       if ( $textarea.css('box-sizing') == 'border-box' ) {
+           height += parseInt( $textarea.css('border-top-width') );
+           height += parseInt( $textarea.css('padding-top') );
+           height += parseInt( $textarea.css('padding-bottom') );
+           height += parseInt( $textarea.css('border-bottom-width') );
+       }
        if (cloneHeight > maxheight) {
```

**Comment by flaviusmatis** [comment]
Just fixed this. Thank you for the idea and sorry for the late answer, I was very busy lately.
